### ISSUE TITLE
Not Awesome

### ISSUE THREAD

**Issue by wchoujaa** [RyanNielson/awesome-unity#104]
this list cannot be awesome unless you add these : 
 
- https://catlikecoding.com/unity/tutorials/
- https://roystan.net/articles/
- https://github.com/brihernandez?tab=repositories

and more

**Comment by vncastanheira** [comment]
lol
but those are good resources, catlikecoding is a classic

**Comment by RyanNielson** [comment]
Go ahead and submit a PR and I'll take a look.
