### ISSUE TITLE
Maintain issue

### ISSUE THREAD

**Issue by jcs090218** [RyanNielson/awesome-unity#119]
@RyanNielson Are you still maintaining this repository? If you are busy and not able to maintain this repository; maybe is good to turn into the community? Like adding more collaborative to help etc. 😖 

Let me know what you think! Thanks! 😄

**Comment by RyanNielson** [comment]
I haven't been doing a lot of Unity development lately, but that may change soon. I'm open to contributions, but unfortunately a lot end up just being self-promotion and it's tough to filter what should and should not be in the list. There hasn't been anyone that's jumped out as contributing lots of high quality PRs, so there's not a natural choice to make and owner or approved contributor of this repo.

**Comment by jcs090218** [comment]
I think there are several rule you can use to filter PRs. Like the following rules are most commonly see from other repo.

1. You cannot add your own project to the list. (Prevent self-promotion)
2. It has to be more than certain amount of stars. (Ensure the quality of the list)

What do you think?

**Comment by jcs090218** [comment]
For example, #118. 

I have tried this package and I personally think is package is qualify to be on the list for few reasons below.

* This isn't my project. (Not self-promotion)
* There are certain amount of stars. (Good!)
* There are people from Microsoft seem to willing to take over the project. (Extra information)
