### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by DataGreed** [RyanNielson/awesome-unity#123]
Lots of links are broken in this project.

E.g. 
- https://www.assetstore.unity3d.com/en/#!/content/17722
- https://www.assetstore.unity3d.com/en/#!/content/908
- https://www.assetstore.unity3d.com/en/#!/content/11653

**Comment by FullStackForger** [comment]
@DataGreed Go with PRs. It is community managed repo ;)

**Comment by DataGreed** [comment]
@FullStackForger sure, here you go: https://github.com/RyanNielson/awesome-unity/pull/125

**Comment by DataGreed** [comment]
cc @RyanNielson
