### ISSUE TITLE
The review time for Pull requests is too long

### ISSUE THREAD

**Issue by EmpireWorld** [RyanNielson/awesome-unity#58]
I was submitted a pull request many days ago and it won't accepted to now.

Please take a look at [Pull requests](https://github.com/RyanNielson/awesome-unity/pulls) and accept the remaining pull requests.

Thanks.

**Comment by RyanNielson** [comment]
I run this repo in my spare time and I try to test out every PR before approving it so things aren't always going to be accepted quickly. 

Please don't add a new PR for this type of thing in the future.

**Comment by MeikelLP** [comment]
Maybe you could add some team members to improve approval speed? I think it may get too big someday to be handled by one person alone.
