### ISSUE TITLE
AI: Crystal AI's and Rain's link seems to be invalid.

### ISSUE THREAD

**Issue by sesky4** [RyanNielson/awesome-unity#72]

**Comment by RyanNielson** [comment]
Any chance you can track down the new URLs and public a pull request? If not I can always try to fix it later on.

**Comment by Zeraphil** [comment]
Crystal AI's link https://github.com/igiagkiozis/CrystalAI

**Comment by RyanNielson** [comment]
Closing this as I just merged a PR that should fix these links. Unfortunately I had to remove Rain because it seems to have been deprecated by its creator.
