### ISSUE TITLE
Modding for Unity?

### ISSUE THREAD

**Issue by markusmo3** [RyanNielson/awesome-unity#87]
Hello there,

i find it sad that there is no central point to find resources related to unity modding. Should those be listed in this repository or in an extra `awesome-unity-modding` list?

Some links i'd like to see there would be:
* https://github.com/0xd4d/dnSpy
* https://github.com/pardeike/Harmony
* https://github.com/0x0ade/MonoMod
* https://github.com/PartialityModding/PartialityLauncher
* https://github.com/Perfare/AssetStudio

If this should land in here i'd make a new Pull Request for it 😄

**Comment by RyanNielson** [comment]
The best place for this is probably in a Pull Request. That's the best place to keep track of them. A modding section could be useful in this list since information about modding Unity can be hard to find.
